export const DEFAULT_SIGNAL = {
    id: '1',
    type: 'oscillator',
    name: 'CLK 1',
    period: 100,
    delay: 0,
    edgeCount: -1,
    inverted: false,
    color: '#000000'
};

export const DEFAULT_STATE = {
    diagramName: 'Untitled',
    signals: [{ ...DEFAULT_SIGNAL }],
    boldEdges: [],
    edgeArrows: [],
    guides: [],
    zones: [],
    links: [],
    measurements: [],
    layers: {
        guides: [],
        zones: [],
        links: [],
        edgeArrows: [],
        measurements: []
    },
    legend: {
        entries: [],
        layout: {
            x: null,
            y: null,
            padding: 8,
            gap: 6,
            border: true,
            borderWidth: 1,
            cornerRadius: 0
        }
    },
    settings: {
        duration: 350,
        spacing: 60,
        signalSpacingMode: 'pitch',
        timeScale: 2.0,
        lineWidth: 2,
        boldWeight: 3.0,
        uniformizeGuide: false,
        uniformizeLink: false,
        uniformizeZone: false,
        uniformizeBoldEdge: false,
        uniformizeEdgeArrow: false,
        autoGuide: true,
        autoLink: true,
        autoZone: true,
        autoBoldEdge: true,
        autoEdgeArrow: true,
        edgeArrowType: 'filled',
        edgeArrowSize: 10,
        edgeArrowRatio: 1.4,
        edgeArrowColor: '#000000',
        edgeArrowLabelText: '',
        edgeArrowLabelSize: 10,
        edgeArrowLabelPosition: 'above',
        fontSize: 10,
        fontFamily: 'Times New Roman, serif',
        boldLabels: true,
        labelJustify: 'start',
        labelX: 0,
        labelYOffset: -5,
        counterFontSize: 10,
        linkLineWidth: 1.2,
        linkStyle: 'dashed',
        linkColor: '#000000',
        arrowSize: 10,
        linkDashLength: 8,
        linkDashGap: 4,
        linkStartMarker: 'none',
        linkEndMarker: 'arrow',
        guideLineWidth: 1.0,
        guideStyle: 'dotted',
        guideDashLength: 2,
        guideDashGap: 2,
        guideExtraHeight: 20,
        guideUseRelativeExtents: false,
        guideUpperExtension: 120,
        guideLowerExtension: 240,
        oscWaveHeight: 30,
        counterWaveHeight: 24,
        zoneBorderWidth: 0.8,
        zonePatternWidth: 0.8,
        hatchType: 'hatch-45',
        zoneColor: '#000000'
    }
};
